### ISSUE TITLE
The stack deployment failed

### ISSUE THREAD

**Issue by anuppoudel54** [scottpedia/aws-client-vpn-setup#1]
Deployment initiated. The program will refresh every 3 seconds to check the progress of deployment. The timeout is 5 mimutes.
>>>>>>>>>>>>>>>>>>The stack deployment failed.
Errors occured during the deployment process.
 Program Exits.
Traceback (most recent call last):
  File "/Users/anuppoudel/stuff/aws-client-vpn-setup/./client-vpn-aio", line 854, in <module>
    deploy_cloudformation_template()
  File "/Users/anuppoudel/stuff/aws-client-vpn-setup/./client-vpn-aio", line 712, in deploy_cloudformation_template
    raise Exception("The stack deployment failed.")
Exception: The stack deployment failed.

From the cloudformation logs
```
Request content has changed. Kindly re-check the request content and the client token 011200a9-c769-4627-*****-******used. (Service: AmazonEC2; Status Code: 400; Error Code: IdempotentParameterMismatch; Request ID: 3e49e34e-8292; Proxy: null)
```

**Comment by anuppoudel54** [comment]
Worked right after posting this issue and retrying
